"""link contacts to users

Revision ID: 09328acea8bf
Revises: 1b0df9c9b57e
Create Date: 2026-05-03 23:46:42.193105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "09328acea8bf"
down_revision: Union[str, Sequence[str], None] = "1b0df9c9b57e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=False)
    op.create_index(op.f("ix_contacts_user_id"), "contacts", ["user_id"], unique=False)
    op.create_unique_constraint(
        "uq_contacts_user_id_email", "contacts", ["user_id", "email"]
    )
    op.create_foreign_key(
        "fk_contacts_user_id_users",
        "contacts",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_contacts_user_id_users", "contacts", type_="foreignkey")
    op.drop_constraint("uq_contacts_user_id_email", "contacts", type_="unique")
    op.drop_index(op.f("ix_contacts_user_id"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=True)
    op.drop_column("contacts", "user_id")
    # ### end Alembic commands ###
